spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kchatdb
    username: marc
    password: -8vz}-^m;i;Cfy;i[[O8lDFh0dy3N_Y-Y]
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    log-request-details:true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
#          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
      client:
        registration:
          google:
            client-id: 512207636442-hp1vtt2ec05tijpfpfpil7vscg1h3ids.apps.googleusercontent.com
            client-secret: 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
#          github:
#            clientId: 86e820011747d0a2d765
#            clientSecret: 8d8ea171793b42035cbbee8a4f558ef9d23167b3
#            redirectUri: https://www.wewehappy.com/login/oauth2/code/github
#            scope:
#              - user:email
#              - read:user

application:
  security:
    jwt:
      secret-key: 34klsopflv0sdf9voebjx734vlg7edcfbhkep0dd054083sl4csri39dm78x34m9
      expiration: 1200000 # 20 minutes
      refresh-token:
        expiration: 604800000 # 7 days


logging:
  level:
    org:
      springframework:
        security: DEBUG
        security.access: DEBUG
        autoconfigure.security: DEBUG
        web: DEBUG
        hibernate: DEBUG
  file:
    path: /var/log/spring
    level:
        org:
          springframework:
            security: DEBUG
            security.access: DEBUG
            web: DEBUG
            hibernate: DEBUG
